# -*- coding: utf-8 -*-
"""Immutable release identity, outcomes, reason codes, and safety limits."""
import re

DISCLAIMER = (
    "ARCHITECTURE DEMONSTRATION ONLY - NOT FINANCIAL ADVICE - "
    "NO LIVE TRADING - NO PROFIT CLAIMS"
)
PERFORMANCE_DISCLAIMER = (
    "Hypothetical research results from paper-only processing; they do not "
    "represent actual trading, predict future returns, or authorize a trade."
)

PROJECT_ID = "PRJ-017"
RELEASE_ID = "TRL-R1"
CHECKPOINT_ID = "TRL-R1-004"
ENGINE_NAME = "ALSAKKAF_TRL_CAUSAL_KERNEL"
ENGINE_VERSION = "1.0.0"
COMMITTED_BASE_REVISION = "05f7ba9"
ENGINE_SOURCE_DIGEST_ALGORITHM = "SHA-256"
ENGINE_SOURCE_NORMALIZATION = "UTF-8; CRLF_AND_CR_TO_LF"
PUBLIC_SCHEMA_TYPE_POLICY = (
    "EXACT BUILT-INS ONLY: dict, list, str, int, float; "
    "numeric bool rejected; finite/range rules apply"
)
OUTPUT_SCHEMA_VERSION = "1.0.0"
STRATEGY_ID = "SMA-001"
STRATEGY_VERSION = "1.0.0"
STRATEGY_FAMILY = "SMA_CROSS_LONG_ONLY"
STRATEGY_STATUS = "EXPERIMENTAL_RESEARCH_ONLY"

STARTING_CASH = 100.0
ACCOUNTING_UNIT = "paper_units_not_real_currency"
MAX_POSITION_PCT = 5.0
DRAWDOWN_HALT_PCT = -15.0
MAX_OPEN_POSITIONS = 1
COMMISSION_RATE = 0.0005
SLIPPAGE_RATE = 0.0005
SUPPORTED_ASSET_CLASSES = frozenset(("equity", "fx", "commodity", "index"))

OUTCOME_SIGNAL = "SIGNAL_SCHEDULED"
OUTCOME_FILL = "HYPOTHETICAL_FILL"
OUTCOME_NO_TRADE = "NO_TRADE"
OUTCOME_BLOCKED = "BLOCKED"
OUTCOME_HALT = "HALT"
OUTCOME_NO_FILL = "NO_FILL"

NO_TRADE_INSUFFICIENT_HISTORY = "NO_TRADE_INSUFFICIENT_HISTORY"
NO_TRADE_NO_CROSS = "NO_TRADE_NO_CROSS"
NO_TRADE_ALREADY_POSITIONED = "NO_TRADE_ALREADY_POSITIONED"
NO_TRADE_NO_OPEN_POSITION = "NO_TRADE_NO_OPEN_POSITION"
BLOCKED_INVALID_INPUT = "BLOCKED_INVALID_INPUT"
BLOCKED_INVALID_STRATEGY_PARAMETERS = "BLOCKED_INVALID_STRATEGY_PARAMETERS"
BLOCKED_POSITION_LIMIT = "BLOCKED_POSITION_LIMIT"
BLOCKED_DRAWDOWN_HALT = "BLOCKED_DRAWDOWN_HALT"
BLOCKED_RISK_OVERRIDE_ATTEMPT = "BLOCKED_RISK_OVERRIDE_ATTEMPT"
BLOCKED_INCREASE_TO_LOSER = "BLOCKED_INCREASE_TO_LOSER"
BLOCKED_REPRODUCIBILITY_ERROR = "BLOCKED_REPRODUCIBILITY_ERROR"
NO_FILL_END_OF_DATA = "NO_FILL_END_OF_DATA"

ENTRY_SIGNAL_SCHEDULED = "ENTRY_SIGNAL_SCHEDULED"
EXIT_SIGNAL_SCHEDULED = "EXIT_SIGNAL_SCHEDULED"
ENTRY_HYPOTHETICALLY_FILLED = "ENTRY_HYPOTHETICALLY_FILLED"
EXIT_HYPOTHETICALLY_FILLED = "EXIT_HYPOTHETICALLY_FILLED"
OPEN_TERMINAL_POSITION = "OPEN_TERMINAL_POSITION"
COMPLETED_TRADE_HISTORY = "COMPLETED_TRADE_HISTORY"

_PACK_REQUIRED = frozenset(("pack_id", "as_of", "prepared_by", "instruments"))
_PACK_ALLOWED = _PACK_REQUIRED | frozenset(("note",))
_INSTRUMENT_FIELDS = frozenset(
    ("symbol", "asset_class", "data_source", "data_quality_note", "ohlcv")
)
_BAR_FIELDS = frozenset(("date", "open", "high", "low", "close", "volume"))
_STRATEGY_REQUIRED = frozenset(
    ("strategy_id", "strategy_version", "family", "symbol", "fast", "slow",
     "paper_size_pct")
)
_STRATEGY_ALLOWED = _STRATEGY_REQUIRED | frozenset(
    ("name", "lifecycle_status", "author", "review_status", "drawdown_halt_pct")
)
_SEMVER = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+$")
_MAX_SAFE_INPUT_MAGNITUDE = 1e150
_MIN_SAFE_PRICE = 1e-150
_MAX_CANONICAL_INTEGER_BITS = 512
_MAX_CANONICAL_DEPTH = 64
_MAX_CANONICAL_NODES = 100000
