"""Closed capability manifest including narrow TRL-R2-003 MT5 read-only data."""

from . import APPLICATION_VERSION, CHECKPOINT_ID, OPERATING_MODE
from .news_service import STABLE_HEALTH_CODES


IMPLEMENTED = (
    "Local application foundation",
    "Local synthetic demonstration",
    "Interactive synthetic charts",
    "Deterministic report display and download",
    "Release 1 kernel integration",
    "Local governed strategy registry",
    "Local immutable strategy-definition vault",
    "Deterministic registry identities",
    "Separate non-executable research backlog",
    "Registry dashboard and read-only API",
    "Optional local MT5 read-only connector foundation",
    "Broker-native tick and bar normalization",
    "Broker-native symbol-specification display",
    "MT5 connection and data-health reporting",
    "M1, M5, H4 and D1 read-only support",
    "Local MT5 dashboard/API presentation",
    "Optional explicit official-news enablement",
    "Exact governed no-key source allowlist",
    "Safe RSS/Atom and BEA schedule parsing",
    "Deterministic official-news item and event identities",
    "Bounded local official-news cache",
    "Official source health and freshness",
    "Localhost official-news and economic-event APIs",
    "Accessible official-news dashboard presentation",
)

NOT_IMPLEMENTED = (
    "External/live market data",
    "Forward paper portfolio service",
    "Accounts and authentication",
    "Subscriptions and payments",
    "Customer distribution",
    "Broker credentials",
    "Broker connectivity",
    "Assisted execution",
    "Automated execution",
    "External orders",
    "Customer funds or custody",
    "Personalized investment advice",
    "MT5 integration",
    "News feeds",
    "Strategy optimization",
    "Strategy ranking",
    "Regime selection",
    "Order proposals",
    "Cloud backend",
    "Telemetry and analytics",
    "Customer distribution approval",
    "Certified broker compatibility",
    "Live strategy signals",
    "Strategy selection",
    "Regime detection",
    "Broker positions or balances",
    "Commercial news",
    "Full-text aggregation",
    "General web search",
    "Social-media collection",
    "Broker news",
    "Sentiment analysis",
    "AI summarization",
    "Market-impact ranking",
    "Event-to-price joining",
    "Signals and recommendations",
    "Position sizing",
    "Stop-loss/take-profit calculation",
    "Paper or live execution",
    "Cloud synchronization",
    "Payments, subscriptions and telemetry",
)


def capability_manifest():
    """Return a new machine-readable, fail-closed capability manifest."""
    return {
        "application_version": APPLICATION_VERSION,
        "checkpoint": CHECKPOINT_ID,
        "operating_mode": OPERATING_MODE,
        "paper_research_only": True,
        "data_boundary": (
            "COMMITTED_SYNTHETIC_DEFAULT; "
            "OPTIONAL_OPERATOR_ENABLED_LOCAL_MT5_READ_ONLY; "
            "OPTIONAL_OPERATOR_ENABLED_EXACT_OFFICIAL_NEWS_METADATA"
        ),
        "network_boundary": (
            "INBOUND_HTTP_ON_127.0.0.1_ONLY; OUTBOUND_HTTPS_DISABLED_BY_DEFAULT; "
            "EXPLICIT_EXACT_OFFICIAL_ENDPOINTS_ONLY"
        ),
        "implemented": list(IMPLEMENTED),
        "not_implemented": list(NOT_IMPLEMENTED),
        "execution_capability": False,
        "external_order_capability": False,
        "broker_capability": False,
        "credential_storage_capability": False,
        "telemetry": False,
        "atlas_runtime_dependency": False,
        "strategy_registry_checkpoint": "TRL-R2-002",
        "strategy_registry_capability": True,
        "strategy_vault_capability": True,
        "strategy_ranking_capability": False,
        "strategy_optimization_capability": False,
        "regime_selection_capability": False,
        "live_market_data_capability": False,
        "mt5_capability": False,
        "legacy_broad_closed_flag_meanings": {
            "broker_capability": "No account, position, order, or execution integration",
            "live_market_data_capability": "No external or centrally managed live-data service",
            "mt5_capability": "No unrestricted MT5 account or trading integration",
        },
        "local_mt5_read_only_connector_capability": True,
        "local_mt5_tick_and_bar_normalization_capability": True,
        "local_mt5_symbol_specification_capability": True,
        "local_mt5_data_health_capability": True,
        "local_mt5_supported_timeframes": ["M1", "M5", "H4", "D1"],
        "local_mt5_enabled_by_default": False,
        "local_mt5_order_capability": False,
        "news_feed_capability": False,
        "legacy_news_feed_capability_meaning": (
            "No broad, commercial, full-text, broker, social, search, or arbitrary news feed"
        ),
        "official_news_metadata_capability": True,
        "official_economic_schedule_capability": True,
        "official_news_enabled_by_default": False,
        "official_news_no_key_capability": True,
        "official_news_full_text_capability": False,
        "official_news_sentiment_capability": False,
        "official_news_market_impact_capability": False,
        "official_news_event_price_join_capability": False,
        "official_news_stable_health_reason_codes": list(STABLE_HEALTH_CODES),
        "order_proposal_capability": False,
        "cloud_backend_capability": False,
        "accounts_capability": False,
        "subscriptions_capability": False,
        "payments_capability": False,
        "customer_distribution_approved": False,
    }
