"""Local-only operator CLI for the TRL-R2-006 signal-intelligence pipeline.

Every mutating command (``evaluate-strategy``, ``generate-proposal``) talks
directly to a signal-intelligence service built through app.py's single
mode-gated subsystem-construction path — the same path a real server
startup uses — so a CLI-driven evaluation is denied exactly when the
persisted operating mode denies it, with no separate/parallel mode check.
There is no HTTP route that can generate a proposal; this CLI (and the
read-only HTTP status routes) are the only ways to reach the pipeline.

In both available modes (RESEARCH and SYNTHETIC_PAPER), ``app.py.
_signal_service_for_mode`` constructs a durable ``LocalSignalStore``-backed
service (the same one the running application itself uses at startup, and
the same store path either mode uses), so ``proposal-history`` in a later,
separate CLI invocation — or the running dashboard's
``/api/signal-proposals`` — sees proposals generated by an earlier
``generate-proposal`` call, regardless of which of the two modes generated
them. Every persisted proposal still carries its own ``operating_mode`` and
``sample_label`` fields, so RESEARCH and SYNTHETIC_PAPER records sharing
that one durable store are never indistinguishable.
``export-proposal``/``validate-proposal`` operate on a previously saved
proposal JSON file rather than a live history lookup, so they work
regardless of mode or persistence.

Usage (from the Trading_Lab directory):
    python -B -W error -m trading_lab_app.signal_cli signal-status
    python -B -W error -m trading_lab_app.signal_cli list-strategies
    python -B -W error -m trading_lab_app.signal_cli explain-strategy SMA-001
    python -B -W error -m trading_lab_app.signal_cli evaluate-strategy SMA-001 request.json
    python -B -W error -m trading_lab_app.signal_cli generate-proposal SMA-001 request.json
    python -B -W error -m trading_lab_app.signal_cli validate-proposal proposal.json
    python -B -W error -m trading_lab_app.signal_cli proposal-history
    python -B -W error -m trading_lab_app.signal_cli export-proposal proposal.json
    python -B -W error -m trading_lab_app.signal_cli performance-report SMA-001 SYNTHETIC_PAPER
    python -B -W error -m trading_lab_app.signal_cli export-performance-report SMA-001 SYNTHETIC_PAPER
    python -B -W error -m trading_lab_app.signal_cli walk-forward-report SMA-001 segments.json
    python -B -W error -m trading_lab_app.signal_cli compare-strategies
"""

import argparse
import json
import sys

from . import signal_data as sd
from . import signal_reporting as reporting
from . import signal_strategy_registry as registry
from .mode_service import ModeService


def _print_json(value):
    print(json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2))


def _build_mode_and_signal_service():
    # Reuse app.py's single combined subsystem-construction path: whatever
    # the persisted operating mode is, this CLI gets exactly the signal
    # service that mode authorizes — never more.
    from .app import _signal_service_for_mode

    mode = ModeService()
    signal_service = _signal_service_for_mode(mode.current_mode)
    return mode, signal_service


def _load_json_file(path):
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def _cmd_signal_status(_args):
    _mode, signal_service = _build_mode_and_signal_service()
    _print_json(signal_service.status_document())
    return 0


def _cmd_list_strategies(_args):
    _print_json({"schema_version": registry.REGISTRY_SCHEMA_VERSION, "strategies": registry.list_strategies()})
    return 0


def _cmd_explain_strategy(args):
    record = registry.get_strategy(args.strategy_id)
    if record is None:
        print("Unknown strategy_id {!r}.".format(args.strategy_id), file=sys.stderr)
        return 2
    allowed, reason = registry.executable_status(args.strategy_id)
    _print_json({"record": record, "executable_now": allowed, "reason_code": reason})
    return 0


def _run_evaluation(args):
    mode, signal_service = _build_mode_and_signal_service()
    if not signal_service.enabled:
        print(
            "Signal intelligence is unavailable in the {} operating mode.".format(mode.current_mode),
            file=sys.stderr,
        )
        return None, 2
    request_payload = _load_json_file(args.request_file)
    request_payload = dict(request_payload)
    request_payload["strategy_id"] = args.strategy_id
    observation = request_payload["market_observation"]
    evidence_event = signal_service.append_market_observation(
        request_payload["instrument"],
        request_payload["market_observation_occurred_at_utc"],
        request_payload["market_observation_first_observed_at_utc"],
        observation,
    )
    request_payload["market_data_observation_id"] = evidence_event["timeline_event_id"]
    try:
        result = signal_service.generate_proposal(request_payload)
    except Exception as error:  # noqa: BLE001 - CLI boundary, print and exit non-zero
        print("Evaluation failed: {}".format(error), file=sys.stderr)
        return None, 1
    return result, 0


def _cmd_evaluate_strategy(args):
    result, code = _run_evaluation(args)
    if result is None:
        return code
    _print_json({
        "side": result["proposal"]["side"],
        "rejection_reasons": result["proposal"]["rejection_reasons"],
        "role_results": result["proposal"]["role_results"],
        "confidence_score": result["proposal"]["confidence_score"],
    })
    return 0


def _cmd_generate_proposal(args):
    result, code = _run_evaluation(args)
    if result is None:
        return code
    _print_json(result["proposal"])
    return 0


def _cmd_validate_proposal(args):
    proposal = _load_json_file(args.proposal_file)
    try:
        clean = sd.validate_signal_proposal(proposal)
    except sd.SignalValidationError as error:
        _print_json({"valid": False, "error": str(error)})
        return 1
    _print_json({"valid": True, "proposal_id": clean["proposal_id"]})
    return 0


def _cmd_proposal_history(_args):
    _mode, signal_service = _build_mode_and_signal_service()
    _print_json(signal_service.proposal_history_document())
    return 0


def _cmd_export_proposal(args):
    proposal = _load_json_file(args.proposal_file)
    clean = sd.validate_signal_proposal(proposal)
    _print_json(clean)
    return 0


def _cmd_compare_strategies(_args):
    records = registry.list_strategies()
    comparison = [
        {
            "strategy_id": record["strategy_id"],
            "strategy_version": record["strategy_version"],
            "enabled": record["enabled"],
            "approval_status": record["approval_status"],
            "implementation_status": record["implementation_status"],
            # Neither strategy has completed-trade performance in this
            # checkpoint: SMA-001's crossing direction is approved but its
            # execution geometry is not (STRATEGY_EXECUTION_GEOMETRY_NOT_APPROVED),
            # and FIB-001 has no approved parameters at all
            # (STRATEGY_PARAMETERS_NOT_APPROVED) — never represent either as
            # having executable/completed-trade results here.
            "has_approved_execution_geometry": False,
            "has_completed_trade_performance": False,
        }
        for record in records
    ]
    _print_json({"strategies": comparison})
    return 0


def _matching_proposals(signal_service, strategy_id, sample_label):
    history = signal_service.proposal_history_document()
    return [
        item for item in history["proposals"]
        if item["strategy_id"] == strategy_id and item["sample_label"] == sample_label
    ]


def _build_history_report(args):
    _mode, signal_service = _build_mode_and_signal_service()
    proposals = _matching_proposals(signal_service, args.strategy_id, args.sample_label)
    if not proposals:
        print(
            "No stored proposals for strategy_id={!r} sample_label={!r}.".format(
                args.strategy_id, args.sample_label,
            ),
            file=sys.stderr,
        )
        return None, 2
    observed_times = sorted(item["observed_at_utc"] for item in proposals)
    report = reporting.build_report(
        strategy_id=args.strategy_id,
        strategy_version=proposals[0]["strategy_version"],
        sample_label=args.sample_label,
        proposals=proposals,
        created_at_utc=observed_times[-1],
        sample_start_at_utc=observed_times[0],
        sample_end_at_utc=observed_times[-1],
    )
    return report, 0


def _cmd_performance_report(args):
    report, code = _build_history_report(args)
    if report is None:
        return code
    _print_json(report)
    return 0


def _cmd_export_performance_report(args):
    report, code = _build_history_report(args)
    if report is None:
        return code
    print(reporting.report_markdown(report))
    return 0


def _cmd_walk_forward_report(args):
    _mode, signal_service = _build_mode_and_signal_service()
    proposals = _matching_proposals(signal_service, args.strategy_id, "WALK_FORWARD")
    if not proposals:
        print("No stored WALK_FORWARD proposals for strategy_id={!r}.".format(args.strategy_id), file=sys.stderr)
        return 2
    by_id = {item["proposal_id"]: item for item in proposals}
    segment_definitions = _load_json_file(args.segments_file)
    segments = []
    for definition in segment_definitions:
        segment_proposals = [
            by_id[proposal_id] for proposal_id in definition["proposal_ids"] if proposal_id in by_id
        ]
        segments.append((
            definition["segment_id"], definition["start_at_utc"], definition["end_at_utc"], segment_proposals,
        ))
    observed_times = sorted(item["observed_at_utc"] for item in proposals)
    try:
        report = reporting.build_report(
            strategy_id=args.strategy_id,
            strategy_version=proposals[0]["strategy_version"],
            sample_label="WALK_FORWARD",
            proposals=proposals,
            created_at_utc=observed_times[-1],
            sample_start_at_utc=observed_times[0],
            sample_end_at_utc=observed_times[-1],
            walk_forward_segments=segments,
        )
    except reporting.ReportValidationError as error:
        print("Walk-forward report failed: {}".format(error), file=sys.stderr)
        return 1
    _print_json(report)
    return 0


def build_parser():
    parser = argparse.ArgumentParser(
        prog="trading_lab_app.signal_cli",
        description=(
            "Local-only operator control for the TRL-R2-006 signal-"
            "intelligence pipeline. Every command is mode-gated through the "
            "same ModeService the dashboard server uses; there is no HTTP "
            "route that can generate a proposal."
        ),
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    subparsers.add_parser("signal-status", help="show signal-intelligence engine status")
    subparsers.add_parser("list-strategies", help="list the governed strategy registry")

    explain = subparsers.add_parser("explain-strategy", help="explain one registered strategy")
    explain.add_argument("strategy_id", help="exact strategy ID, e.g. SMA-001")

    evaluate = subparsers.add_parser("evaluate-strategy", help="run the pipeline, show role results only")
    evaluate.add_argument("strategy_id", help="exact strategy ID, e.g. SMA-001")
    evaluate.add_argument("request_file", help="path to a TRL_SIGNAL_EVALUATION_REQUEST.v1 JSON file")

    generate = subparsers.add_parser("generate-proposal", help="run the pipeline, print the full proposal")
    generate.add_argument("strategy_id", help="exact strategy ID, e.g. SMA-001")
    generate.add_argument("request_file", help="path to a TRL_SIGNAL_EVALUATION_REQUEST.v1 JSON file")

    validate = subparsers.add_parser("validate-proposal", help="validate a saved proposal JSON file")
    validate.add_argument("proposal_file", help="path to a TRL_SIGNAL_PROPOSAL.v1 JSON file")

    subparsers.add_parser("proposal-history", help="show the durable proposal/audit history")

    export = subparsers.add_parser("export-proposal", help="re-validate and re-emit a saved proposal JSON file")
    export.add_argument("proposal_file", help="path to a TRL_SIGNAL_PROPOSAL.v1 JSON file")

    subparsers.add_parser("compare-strategies", help="show every registered strategy side by side")

    performance = subparsers.add_parser(
        "performance-report", help="build a research performance report from durable history (JSON)",
    )
    performance.add_argument("strategy_id", help="exact strategy ID, e.g. SMA-001")
    performance.add_argument("sample_label", help="one governed sample label, e.g. SYNTHETIC_PAPER")

    export_performance = subparsers.add_parser(
        "export-performance-report", help="build a research performance report from durable history (Markdown)",
    )
    export_performance.add_argument("strategy_id", help="exact strategy ID, e.g. SMA-001")
    export_performance.add_argument("sample_label", help="one governed sample label, e.g. SYNTHETIC_PAPER")

    walk_forward = subparsers.add_parser(
        "walk-forward-report", help="build a WALK_FORWARD report from durable history and a segment-boundary file",
    )
    walk_forward.add_argument("strategy_id", help="exact strategy ID, e.g. SMA-001")
    walk_forward.add_argument(
        "segments_file",
        help="JSON list of {segment_id, start_at_utc, end_at_utc, proposal_ids}",
    )

    return parser


def main(argv=None):
    args = build_parser().parse_args(argv)
    handlers = {
        "signal-status": _cmd_signal_status,
        "list-strategies": _cmd_list_strategies,
        "explain-strategy": _cmd_explain_strategy,
        "evaluate-strategy": _cmd_evaluate_strategy,
        "generate-proposal": _cmd_generate_proposal,
        "validate-proposal": _cmd_validate_proposal,
        "proposal-history": _cmd_proposal_history,
        "export-proposal": _cmd_export_proposal,
        "compare-strategies": _cmd_compare_strategies,
        "performance-report": _cmd_performance_report,
        "export-performance-report": _cmd_export_performance_report,
        "walk-forward-report": _cmd_walk_forward_report,
    }
    return handlers[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
