#!/usr/bin/env python3
"""
Atlas Runtime v1.2 (PRJ-009) - local CEO assistant tool for ALSAKKAF HOLDING GROUP.

Python standard library only. No network access. No external packages.
No credentials are ever read, requested, or stored by this tool.

Usage:
    py atlas.py <command>

Commands:
    health-check        Verify the launch package is present, safe, and readable.
    brief               Generate a daily CEO briefing from the trackers.
    score-leads         Score real leads in Lead_Tracker.csv (never invents leads).
    dashboard           Regenerate docs/atlas-dashboard-data.js from real tracker counts.
    proposal            Generate a proposal draft for the AI Workflow Starter Pack.
    outreach            Generate personalized outreach drafts (never sends anything).
    content-pack        Generate a daily multi-platform content pack.
    delivery-checklist  Generate a client delivery checklist.
    payment-report      Report paid/unpaid/payment-link-sent status from the pipeline.
    war-room            Run brief + dashboard + payment-report + content-pack together.
    revenue-sprint      Generate the PRJ-009 revenue sprint status report.
    ai-agent-proposal   Generate a proposal draft for the AI Agent Starter Pack ($450).
    ai-agent-delivery   Generate the AI Agent Starter Pack delivery checklist.
    first-5-outreach    Generate the first-5 outreach execution pack (drafts only).
"""

import argparse
import csv
import json
import re
import sys
from datetime import datetime
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[2]
CONFIG_PATH = SCRIPT_DIR / "atlas_config.json"

CREDENTIAL_PATTERN = re.compile(
    r"(?i)\b(password|passwd|pwd|secret|api[_-]?key|apikey|client[_-]?secret|"
    r"private[_-]?key|access[_-]?token|refresh[_-]?token|recovery[_-]?code|"
    r"2fa[_-]?code|bank[_-]?account|card[_-]?number)\b\s*[:=]\s*[^\s,\"']{4,}"
)

PLACEHOLDER_MARKERS = (
    "example only",
    "template row",
    "placeholder row",
    "not a real",
    "sample row",
)


# ---------------------------------------------------------------------------
# Core helpers
# ---------------------------------------------------------------------------

def load_config():
    if not CONFIG_PATH.exists():
        print(f"[FAIL] Config file missing: {CONFIG_PATH}")
        sys.exit(1)
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def rp(relative_path):
    """Resolve a repo-relative path to an absolute Path."""
    return REPO_ROOT / relative_path


def now_iso():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def today():
    return datetime.now().strftime("%Y-%m-%d")


def ensure_dir(path: Path):
    path.mkdir(parents=True, exist_ok=True)


def read_csv_rows(path: Path):
    """Read a CSV into a list of dicts. Returns [] with a warning if missing/unreadable."""
    if not path.exists():
        print(f"  [WARN] Missing tracker file: {path}")
        print("         Fix: confirm the Revenue Operations / Content Operations folders were created.")
        return []
    try:
        with open(path, "r", encoding="utf-8-sig", newline="") as f:
            reader = csv.DictReader(f)
            return [row for row in reader if any((v or "").strip() for v in row.values())]
    except Exception as exc:
        print(f"  [WARN] Could not read {path}: {exc}")
        return []


def is_placeholder_row(row: dict) -> bool:
    """A row is a placeholder/example if any field or ID marks it as such."""
    for key, value in row.items():
        if not value:
            continue
        text = str(value).lower()
        if any(marker in text for marker in PLACEHOLDER_MARKERS):
            return True
        if key and key.strip().lower().endswith("id") and text.strip().upper().startswith("EXAMPLE"):
            return True
    return False


def real_rows(rows):
    return [r for r in rows if not is_placeholder_row(r)]


def write_output(path: Path, content: str):
    ensure_dir(path.parent)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  [OK] Wrote {path.relative_to(REPO_ROOT)}")


def doc_info_block(command: str) -> list:
    """Standard AOS-style Document Information block for every Atlas Runtime generated report."""
    return [
        "## Document Information",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| Generated By | Atlas Runtime (`atlas.py {command}`) |",
        "| Status | Draft - Local Output |",
        f"| Date | {today()} |",
        "| Related Documents | PRJ-007, PRJ-009, ARUN-001 |",
        "",
        "---",
        "",
    ]


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------

def compute_metrics(cfg):
    paths = cfg["paths"]

    leads = real_rows(read_csv_rows(rp(paths["lead_tracker"])))
    outreach = real_rows(read_csv_rows(rp(paths["outreach_tracker"])))
    pipeline = real_rows(read_csv_rows(rp(paths["client_pipeline"])))
    content = real_rows(read_csv_rows(rp(paths["content_calendar"])))
    analytics = real_rows(read_csv_rows(rp(paths["content_analytics"])))

    leads_found = len(leads)
    leads_qualified = len([
        r for r in leads
        if (r.get("Lead Score", "").strip() not in ("", "0"))
        and r.get("Status", "").strip().lower() not in ("", "new")
    ])

    outreach_drafted = len(outreach)
    outreach_sent = len([r for r in outreach if r.get("Date Sent", "").strip()])
    outreach_approved = len([r for r in outreach if r.get("CEO Approved", "").strip().lower() == "yes"])

    pipeline_active = len(pipeline)
    payments_received = len([r for r in pipeline if r.get("Payment Status", "").strip().lower() == "paid"])
    payment_links_sent = len([r for r in pipeline if r.get("Payment Link Sent", "").strip().lower() == "yes"])
    revenue_collected = 0.0
    for r in pipeline:
        if r.get("Payment Status", "").strip().lower() == "paid":
            try:
                revenue_collected += float(str(r.get("Quoted Price USD", "0")).replace("$", "").strip() or 0)
            except ValueError:
                pass

    content_drafted = len(content)
    content_published = len([r for r in content if r.get("Status", "").strip().lower() == "posted"])

    total_views = 0
    for r in analytics:
        try:
            total_views += int(str(r.get("Views", "0")).strip() or 0)
        except ValueError:
            pass

    return {
        "leads_found": leads_found,
        "leads_qualified": leads_qualified,
        "outreach_drafted": outreach_drafted,
        "outreach_sent": outreach_sent,
        "outreach_approved": outreach_approved,
        "pipeline_active": pipeline_active,
        "payments_received": payments_received,
        "payment_links_sent": payment_links_sent,
        "revenue_collected": revenue_collected,
        "content_drafted": content_drafted,
        "content_published": content_published,
        "total_views": total_views,
        "raw": {
            "leads": leads, "outreach": outreach, "pipeline": pipeline,
            "content": content, "analytics": analytics,
        },
    }


def risk_lines(m, cfg):
    risks = []
    if m["leads_found"] == 0:
        risks.append("No real leads are loaded yet in Lead_Tracker.csv.")
    if m["outreach_sent"] == 0:
        risks.append("No outreach has been sent yet - nothing is CEO-approved to send until reviewed.")
    if m["payments_received"] == 0:
        risks.append(f"$0 collected so far. Revenue is not guaranteed - target ranges are planning estimates only.")
    risks.append("Website is live at https://alsakkafsystems.com - any copy change goes live on the next approved push.")
    risks.append("No credentials are stored by this tool or in this repository.")
    return risks


def guardian_notes(cfg):
    return [
        "Payment link is a public PayPal checkout URL - safe to store, not a credential.",
        "No PayPal login, password, 2FA code, recovery code, API key, or bank detail is stored anywhere in this repo.",
        "Any real account (email, social, website host) requires manual CEO creation and a Guardian security review before use.",
    ]


def ceo_decisions(cfg):
    return [
        "Approve first outreach batch before anything is sent.",
        "Check the professional inboxes daily: hello@, sales@, services@, support@ (alsakkafsystems.com).",
        "Approve each Founding Client Pilot application before accepting it (max 3 pilot projects).",
        "Approve any further landing page copy change before it is pushed live.",
    ]


def next_five_actions(m):
    if m["leads_found"] == 0:
        return [
            "Approve landing page v2 copy.",
            "Publish website (after approval).",
            "Fill first 25 leads in Lead_Tracker.csv.",
            "Approve outreach templates before drafting a batch.",
        ]
    if m["outreach_sent"] == 0:
        return [
            "Run 'atlas.py score-leads' to prioritize leads.",
            "Run 'atlas.py outreach' to draft the first batch.",
            "CEO reviews and approves the drafted batch.",
            "Send the first 5 personalized messages manually.",
            "Log each send in Outreach_Tracker.csv.",
        ]
    return [
        "Follow up on sent outreach per the follow-up schedule.",
        "Run 'atlas.py payment-report' to check pipeline status.",
        "Prepare proposals for any interested leads.",
        "Send the PayPal link only after a client confirms interest.",
        "Run 'atlas.py brief' daily to keep the CEO briefing current.",
    ]


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

def cmd_health_check(cfg, args):
    print("Atlas Runtime - Health Check")
    print("=" * 60)
    ok = True

    print("\n[1] Required files/folders")
    for rel in cfg["health_check_required_paths"]:
        p = rp(rel)
        if p.exists():
            print(f"  [PASS] {rel}")
        else:
            print(f"  [FAIL] Missing: {rel}")
            ok = False

    print("\n[2] Approved payment link present in key files")
    link = cfg["payment_link"]
    for rel in cfg["health_check_payment_link_files"]:
        p = rp(rel)
        if not p.exists():
            print(f"  [WARN] File not found (skipped): {rel}")
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="ignore")
        except Exception as exc:
            print(f"  [WARN] Could not read {rel}: {exc}")
            continue
        if link in text:
            print(f"  [PASS] Link present in {rel}")
        else:
            print(f"  [WARN] Link not found in {rel}")

    print("\n[3] Credential pattern scan (looking for actual key:value secrets, not warnings)")
    hits = scan_for_credentials(cfg)
    if hits:
        ok = False
        for h in hits:
            print(f"  [FAIL] Possible credential value in {h[0]} (line {h[1]}): {h[2]}")
    else:
        print("  [PASS] No credential-like values found.")

    print("\n[4] CSV trackers readable")
    for key in ("lead_tracker", "outreach_tracker", "client_pipeline", "content_calendar", "content_analytics"):
        p = rp(cfg["paths"][key])
        rows = read_csv_rows(p)
        if p.exists():
            print(f"  [PASS] {key}: {len(rows)} data row(s) read")
        else:
            print(f"  [FAIL] {key}: file missing")
            ok = False

    print("\n[5] Dashboard data file present")
    dash = rp(cfg["paths"]["dashboard_data_js"])
    if dash.exists():
        print(f"  [PASS] {cfg['paths']['dashboard_data_js']}")
    else:
        print(f"  [FAIL] Missing: {cfg['paths']['dashboard_data_js']}")
        ok = False

    print("\n" + "=" * 60)
    print("HEALTH CHECK RESULT:", "PASS" if ok else "FAIL")
    print("=" * 60)
    return 0 if ok else 1


def scan_for_credentials(cfg):
    """Return list of (relative_path, line_no, matched_text) for real credential-like values."""
    hits = []
    exts = set(cfg["credential_scan_extensions"])
    for rel_dir in cfg["credential_scan_dirs"]:
        base = rp(rel_dir)
        if not base.exists():
            continue
        for path in base.rglob("*"):
            if not path.is_file() or path.suffix.lower() not in exts:
                continue
            try:
                text = path.read_text(encoding="utf-8", errors="ignore")
            except Exception:
                continue
            for i, line in enumerate(text.splitlines(), start=1):
                m = CREDENTIAL_PATTERN.search(line)
                if m:
                    hits.append((str(path.relative_to(REPO_ROOT)), i, m.group(0)))
    return hits


def cmd_brief(cfg, args):
    print("Atlas Runtime - Generating Daily CEO Briefing")
    m = compute_metrics(cfg)
    date = today()

    lines = []
    lines.append("# ALSAKKAF HOLDING GROUP")
    lines.append("")
    lines.append(f"# Atlas Daily CEO Briefing - {date}")
    lines.append("")
    lines.append("> Auto-generated by Atlas Runtime (atlas.py brief). Local file, not published.")
    lines.append("")
    lines.extend(doc_info_block("brief"))
    lines.append("## Today's Status")
    lines.append("")
    if m["leads_found"] == 0 and m["outreach_sent"] == 0 and m["payments_received"] == 0:
        lines.append("Launch package is built. No real leads, outreach, or payments recorded yet. Ready for CEO to begin execution.")
    else:
        lines.append(f"{m['leads_found']} lead(s) logged, {m['outreach_sent']} outreach message(s) sent, {m['payments_received']} payment(s) received.")
    lines.append("")
    lines.append("## Active Offer")
    lines.append("")
    lines.append(f"{cfg['active_offer']} - ${cfg['price_usd']} {cfg['currency']}, delivered in {cfg['delivery_time']}.")
    lines.append("")
    lines.append("## Active Payment Link")
    lines.append("")
    lines.append(f"{cfg['payment_link']} (the only active payment link; all other offers say \"Request Custom Quote\").")
    lines.append("")
    lines.append("## Leads Summary")
    lines.append("")
    lines.append(f"- Leads found: {m['leads_found']}")
    lines.append(f"- Leads qualified: {m['leads_qualified']}")
    if m["leads_found"] == 0:
        lines.append("- No real leads entered yet. See First_25_Leads_Research_Instructions.md.")
    lines.append("")
    lines.append("## Outreach Summary")
    lines.append("")
    lines.append(f"- Outreach drafted: {m['outreach_drafted']}")
    lines.append(f"- Outreach CEO-approved: {m['outreach_approved']}")
    lines.append(f"- Outreach sent: {m['outreach_sent']}")
    lines.append("")
    lines.append("## Pipeline Summary")
    lines.append("")
    lines.append(f"- Active pipeline entries: {m['pipeline_active']}")
    lines.append(f"- Payment links sent: {m['payment_links_sent']}")
    lines.append(f"- Payments received: {m['payments_received']}")
    lines.append(f"- Revenue collected: ${m['revenue_collected']:.2f} {cfg['currency']}")
    lines.append("")
    lines.append("## Content Summary")
    lines.append("")
    lines.append(f"- Content items drafted/planned: {m['content_drafted']}")
    lines.append(f"- Content items posted: {m['content_published']}")
    lines.append(f"- Total tracked views: {m['total_views']}")
    lines.append("")
    lines.append("## Risks")
    lines.append("")
    for r in risk_lines(m, cfg):
        lines.append(f"- {r}")
    lines.append("")
    lines.append("## CEO Decisions Needed")
    lines.append("")
    for d in ceo_decisions(cfg):
        lines.append(f"- {d}")
    lines.append("")
    lines.append("## Next 5 Actions")
    lines.append("")
    for i, a in enumerate(next_five_actions(m), start=1):
        lines.append(f"{i}. {a}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"Generated: {now_iso()}")
    lines.append("")

    out_dir = rp(cfg["paths"]["output_dir"])
    out_path = out_dir / f"Daily_Briefing_{date}.md"
    write_output(out_path, "\n".join(lines))
    return 0


def cmd_score_leads(cfg, args):
    print("Atlas Runtime - Scoring Leads")
    path = rp(cfg["paths"]["lead_tracker"])
    if not path.exists():
        print(f"  [FAIL] {path} not found. Fix: confirm Revenue Operations folder exists.")
        return 1

    with open(path, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        rows = list(reader)

    real = [r for r in rows if not is_placeholder_row(r)]
    if not real:
        print("  No real leads found in Lead_Tracker.csv - nothing to score yet.")
        print("  Atlas does not invent leads. Add real leads manually or via an approved research action first.")
        report_lines = ["# Atlas Lead Scoring Report", ""]
        report_lines.extend(doc_info_block("score-leads"))
        report_lines.extend([
            f"Generated: {now_iso()}",
            "",
            "No real leads found in Lead_Tracker.csv (only example/placeholder rows present).",
            "Atlas does not invent leads. Add real leads first, then re-run 'atlas.py score-leads'.",
            "",
        ])
        out_path = rp(cfg["paths"]["output_dir"]) / f"Lead_Scoring_Report_{today()}.md"
        write_output(out_path, "\n".join(report_lines))
        return 0

    scored = []
    for row in rows:
        if is_placeholder_row(row):
            continue
        score = 0
        if row.get("Email", "").strip():
            score += 20
        if row.get("Phone", "").strip():
            score += 15
        if row.get("Social Link", "").strip():
            score += 10
        if row.get("Decision Maker", "").strip():
            score += 20
        if row.get("Problem Observed", "").strip():
            score += 20
        if row.get("Offer Match", "").strip():
            score += 15
        score = min(score, 100)
        row["Lead Score"] = str(score)
        scored.append((row.get("Lead ID", "?"), score))

    with open(path, "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    print(f"  [OK] Updated Lead Score for {len(scored)} real lead(s) in Lead_Tracker.csv")

    report_lines = ["# Atlas Lead Scoring Report", ""]
    report_lines.extend(doc_info_block("score-leads"))
    report_lines.extend([f"Generated: {now_iso()}", "", "| Lead ID | Score |", "|---|---|"])
    for lead_id, score in sorted(scored, key=lambda x: -x[1]):
        report_lines.append(f"| {lead_id} | {score} |")
    report_lines.append("")
    report_lines.append("Score is a planning heuristic based on data completeness and stated fit - not a guarantee of conversion.")
    out_path = rp(cfg["paths"]["output_dir"]) / f"Lead_Scoring_Report_{today()}.md"
    write_output(out_path, "\n".join(report_lines))
    return 0


def cmd_dashboard(cfg, args):
    print("Atlas Runtime - Updating Local Dashboard Data")
    m = compute_metrics(cfg)
    dash_path = rp(cfg["paths"]["dashboard_data_js"])

    leads_note = "No real leads entered yet." if m["leads_found"] == 0 else f"{m['leads_found']} real lead(s) on file."
    website_status = "Live at https://alsakkafsystems.com (GitHub Pages + custom domain)"

    risks = risk_lines(m, cfg)
    decisions = ceo_decisions(cfg)
    actions = next_five_actions(m)
    guardian = guardian_notes(cfg)

    data = {
        "founderMission": "Convert AOS into real revenue, starting with AI Services.",
        "revenueTargetNote": "Planning reference only (STRAT-005): first 30-day target revenue is $7,500-equivalent. Not a guarantee.",
        "revenueCollected": round(m["revenue_collected"], 2),
        "paymentsReceived": m["payments_received"],
        "activeOffer": f"{cfg['active_offer']} - ${cfg['price_usd']} {cfg['currency']}",
        "secondOffer": (
            f"{cfg['second_offer']['name']} - ${cfg['second_offer']['price_usd']} "
            f"{cfg['second_offer'].get('currency', 'USD')} - {cfg['second_offer'].get('payment_status', 'Request Custom Quote')}"
            if cfg.get("second_offer") else ""
        ),
        "paymentLink": cfg["payment_link"],
        "paymentLinkStatus": "Active - only approved link",
        "currency": cfg["currency"],
        "leadsFound": m["leads_found"],
        "leadsQualified": m["leads_qualified"],
        "leadsNote": leads_note,
        "outreachDrafted": m["outreach_drafted"],
        "outreachSent": m["outreach_sent"],
        "pipelineActive": m["pipeline_active"],
        "paymentLinksSent": m["payment_links_sent"],
        "contentDrafted": m["content_drafted"],
        "contentPublished": m["content_published"],
        "totalViews": m["total_views"],
        "websiteStatus": website_status,
        "activePartners": cfg["active_partners"],
        "proposedPartners": cfg["proposed_partners_note"],
        "ceoDecisions": decisions,
        "risks": risks,
        "guardianNotes": guardian,
        "nextActions": actions,
        "lastUpdated": now_iso(),
    }

    js = []
    js.append("// Atlas CEO Dashboard - local static data file.")
    js.append("// Auto-generated by Atlas Runtime (atlas.py dashboard). Do not hand-edit numeric fields; edit trackers instead.")
    js.append("// No external calls, no analytics, no tracking, no secrets.")
    js.append("")
    js.append("const atlasDashboardData = " + json.dumps(data, indent=2, ensure_ascii=False) + ";")
    js.append("")
    js.append("""function renderAtlasDashboard(data) {
  const setText = (id, value) => {
    const el = document.getElementById(id);
    if (el) el.textContent = value;
  };

  const setList = (id, items) => {
    const el = document.getElementById(id);
    if (!el) return;
    el.innerHTML = "";
    (items || []).forEach((item) => {
      const li = document.createElement("li");
      li.textContent = item;
      el.appendChild(li);
    });
  };

  setText("founder-mission", data.founderMission);
  setText("revenue-target-note", data.revenueTargetNote);
  setText("revenue-collected", "$" + data.revenueCollected);
  setText("payments-received", data.paymentsReceived);
  setText("active-offer", data.activeOffer);
  setText("second-offer", data.secondOffer || "");
  setText("payment-link", data.paymentLink);
  setText("payment-link-status", data.paymentLinkStatus);
  setText("leads-found", data.leadsFound);
  setText("leads-qualified", data.leadsQualified);
  setText("leads-note", data.leadsNote || "");
  setText("outreach-drafted", data.outreachDrafted);
  setText("outreach-sent", data.outreachSent);
  setText("pipeline-active", data.pipelineActive);
  setText("payment-links-sent", data.paymentLinksSent);
  setText("content-drafted", data.contentDrafted);
  setText("content-published", data.contentPublished);
  setText("total-views", data.totalViews);
  setText("website-status", data.websiteStatus);
  setText("last-updated", data.lastUpdated);

  setList("active-partners-list", data.activePartners);
  setText("proposed-partners-note", data.proposedPartners);
  setList("ceo-decisions-list", data.ceoDecisions);
  setList("risks-list", data.risks);
  setList("guardian-notes-list", data.guardianNotes);
  setList("next-actions-list", data.nextActions);
}

document.addEventListener("DOMContentLoaded", function () {
  renderAtlasDashboard(atlasDashboardData);
});""")

    write_output(dash_path, "\n".join(js) + "\n")
    print(f"  Leads: {m['leads_found']} | Outreach sent: {m['outreach_sent']} | Revenue: ${m['revenue_collected']:.2f}")
    return 0


def cmd_proposal(cfg, args):
    print("Atlas Runtime - Generating Proposal Draft")
    client = args.client.strip() if getattr(args, "client", None) else "[Client Name]"
    date = today()

    lines = []
    lines.append("# AOS AI Services - Proposal")
    lines.append("")
    lines.append(f"Prepared for: {client}")
    lines.append(f"Date: {date}")
    lines.append("")
    lines.extend(doc_info_block("proposal"))
    lines.append("## Offer")
    lines.append("")
    lines.append(f"{cfg['active_offer']} - ${cfg['price_usd']} {cfg['currency']}")
    lines.append(f"Positioning: {cfg.get('offer_positioning', '')}")
    lines.append(f"Delivery time: {cfg['delivery_time']}")
    lines.append("")
    lines.append("Payments are processed in USD.")
    lines.append("")
    lines.append("## 3 Automations for the Price of One")
    lines.append("")
    for i, a in enumerate(cfg.get("automations", []), start=1):
        lines.append(f"**{i}. {a['name']}**")
        for item in a["includes"]:
            lines.append(f"- {item}")
        lines.append("")
    lines.append("One scoped engagement - not three times the work, three times the outcome.")
    lines.append("")
    lines.append("## Not Sure This Is the Right Fit?")
    lines.append("")
    lines.append("We recommend a short, free consultation call before payment if your needs go beyond a single standard workflow. This proposal assumes a scoped, single-workflow engagement.")
    lines.append("")
    lines.append("## Payment")
    lines.append("")
    lines.append(f"Once you're ready to proceed: {cfg['payment_link']}")
    lines.append("")
    lines.append("Active payment links exist only for the $399 AI Workflow Starter Pack and the $450 AI Agent Starter Pack. Any other service is Request Custom Quote until a separate link is approved.")
    lines.append("")
    lines.append("## Next Steps")
    lines.append("")
    lines.append("1. Confirm scope on a short intake call.")
    lines.append("2. Pay via the link above when ready.")
    lines.append("3. Receive intake questions and begin delivery.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("**Note:** This is a draft. Final proposal requires CEO review before sending to any real client.")
    lines.append("")
    lines.append(f"Generated: {now_iso()}")
    lines.append("")

    safe_name = re.sub(r"[^A-Za-z0-9_-]+", "_", client).strip("_") or "Blank"
    out_path = rp(cfg["paths"]["proposal_drafts_dir"]) / f"Proposal_{safe_name}_{date}.md"
    write_output(out_path, "\n".join(lines))
    return 0


def cmd_outreach(cfg, args):
    print("Atlas Runtime - Generating Outreach Drafts")
    date = today()

    drafts = [
        ("Cold Email", "Email",
         "Subject: A quick idea for [Company Name]\n\n"
         "Hi [First Name],\n\n"
         "I noticed [specific observation about their business]. We put together a small, "
         "documented AI workflow review for businesses in a similar spot - it's a scoped, "
         "one-time package, not a subscription.\n\n"
         "Would it be useful to see what that could look like for [Company Name]? Happy to "
         "send a short outline, no pressure either way.\n\n"
         "Best,\n[Your Name]\nALSAKKAF HOLDING GROUP - AOS AI Services"),
        ("LinkedIn DM", "LinkedIn",
         "Hi [First Name] - saw [specific detail]. I help small businesses turn repetitive "
         "work into a documented AI workflow (scoped, one-time package). Worth a quick look "
         "for [Company Name]? Happy to share more, no pressure."),
        ("Instagram DM", "Instagram",
         "Hey [First Name]! Love what you're building at [Company Name]. I put together a "
         "simple AI workflow package for small businesses - would you want a quick look at "
         "what it could do for you?"),
        ("WhatsApp Message", "WhatsApp",
         "Hi [First Name], this is [Your Name] from AOS AI Services. [Personal context - "
         "use only with a warm/known contact]. I put together a small AI workflow package "
         "for businesses like [Company Name] - want me to send a short outline?"),
    ]

    lines = ["# Atlas Outreach Batch Draft", ""]
    lines.extend(doc_info_block("outreach"))
    lines.extend([f"Generated: {now_iso()}", "",
             "**CEO Approval Required.** Nothing in this batch has been sent. Personalize every "
             "bracketed placeholder before any message goes out. The PayPal payment link must not "
             "appear in first-contact/cold messages.", "", "---", ""])
    for name, channel, body in drafts:
        lines.append(f"## {name} ({channel})")
        lines.append("")
        lines.append("```text")
        lines.append(body)
        lines.append("```")
        lines.append("")
        lines.append(f"CEO Approved: Pending")
        lines.append("")
        lines.append("---")
        lines.append("")

    out_path = rp(cfg["paths"]["outreach_drafts_dir"]) / f"Outreach_Batch_{date}.md"
    write_output(out_path, "\n".join(lines))
    return 0


def cmd_content_pack(cfg, args):
    print("Atlas Runtime - Generating Daily Content Pack")
    date = today()

    m = compute_metrics(cfg)
    upcoming = m["raw"]["content"][:5]

    lines = ["# Atlas Daily Content Pack", ""]
    lines.extend(doc_info_block("content-pack"))
    lines.extend([f"Date: {date}", f"Generated: {now_iso()}", "",
              "No fake claims. No guaranteed-income claims. Original content only - see "
              "Multi_Platform_Content_Execution_Plan.md and Short_Form_Video_Script_Bank.md "
              "for the full source material.", "", "---", ""])

    if upcoming:
        lines.append("## From Content_Calendar.csv")
        lines.append("")
        for row in upcoming:
            lines.append(f"- {row.get('Date','?')} | {row.get('Platform','?')} | {row.get('Topic/Title','?')} | Status: {row.get('Status','?')}")
        lines.append("")
        lines.append("---")
        lines.append("")

    platforms = [
        ("LinkedIn", "A short, professional post sharing one practical AI-for-small-business insight. Soft CTA - no hard sell."),
        ("Threads", "A short, conversational take on one lesson from building AOS this week."),
        ("Instagram", "A visual-first caption pairing a behind-the-scenes shot with one honest insight. 5-8 relevant hashtags max."),
        ("TikTok", "A punchy, honest hook about one small-business workflow problem, 30-60 seconds."),
        ("YouTube Shorts", "A 30-60 second script: hook, one clear point, soft CTA to follow for more."),
    ]
    lines.append("## Draft Slots (fill from Short_Form_Video_Script_Bank.md / AOS_Service_Content_Posts.md)")
    lines.append("")
    for platform, note in platforms:
        lines.append(f"### {platform}")
        lines.append("")
        lines.append(f"[Placeholder] {note}")
        lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("**CEO Approval Required** before anything here is published.")
    lines.append("")

    out_path = rp(cfg["paths"]["content_packs_dir"]) / f"Content_Pack_{date}.md"
    write_output(out_path, "\n".join(lines))
    return 0


def cmd_delivery_checklist(cfg, args):
    print("Atlas Runtime - Generating Client Delivery Checklist")
    client = args.client.strip() if getattr(args, "client", None) else "[Client Name]"
    date = today()

    lines = ["# Client Delivery Checklist", ""]
    lines.extend(doc_info_block("delivery-checklist"))
    lines.extend([f"Client: {client}", f"Offer: {cfg['active_offer']} - ${cfg['price_usd']} {cfg['currency']} ({cfg.get('offer_positioning', '')})",
              f"Delivery time: {cfg['delivery_time']}", f"Generated: {now_iso()}", "", "---", ""])
    lines.append("## Delivery Steps")
    lines.append("")
    lines.append("- [ ] Client intake form completed")
    for a in cfg.get("automations", []):
        lines.append(f"- [ ] {a['name']} delivered")
        for item in a["includes"]:
            lines.append(f"      - [ ] {item}")
    lines.append("- [ ] Final client report sent")
    lines.append("- [ ] Client sign-off received")
    lines.append("- [ ] Lessons learned logged (internal)")
    lines.append("")
    lines.append("See `01_Holding_Company/04_Operations/05_Client_Delivery/` for the full workflow and templates.")
    lines.append("")

    safe_name = re.sub(r"[^A-Za-z0-9_-]+", "_", client).strip("_") or "Blank"
    out_path = rp(cfg["paths"]["client_delivery_dir"]) / f"Delivery_Checklist_{safe_name}_{date}.md"
    write_output(out_path, "\n".join(lines))
    return 0


def cmd_payment_report(cfg, args):
    print("Atlas Runtime - Generating Payment Report")
    m = compute_metrics(cfg)
    date = today()
    pipeline = m["raw"]["pipeline"]

    lines = ["# Atlas Payment Report", ""]
    lines.extend(doc_info_block("payment-report"))
    lines.extend([f"Generated: {now_iso()}", "",
              "This report reads Client_Pipeline.csv only. It never connects to PayPal and never "
              "requests or stores PayPal credentials.", "", "---", ""])
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Active pipeline entries: {m['pipeline_active']}")
    lines.append(f"- Payment links sent: {m['payment_links_sent']}")
    lines.append(f"- Payments received: {m['payments_received']}")
    lines.append(f"- Revenue collected: ${m['revenue_collected']:.2f} {cfg['currency']}")
    lines.append("")
    if not pipeline:
        lines.append("No real pipeline entries yet (only example/placeholder rows present in Client_Pipeline.csv).")
        lines.append("")
        lines.append("Next Action: log a real client here once a lead confirms interest and a price is quoted.")
    else:
        lines.append("## Detail")
        lines.append("")
        for r in pipeline:
            lines.append(f"- {r.get('Company Name','?')} | {r.get('Service Interested','?')} | "
                          f"${r.get('Quoted Price USD','?')} | Link sent: {r.get('Payment Link Sent','?')} | "
                          f"Status: {r.get('Payment Status','?')} | Delivery: {r.get('Delivery Status','?')}")
    lines.append("")

    out_path = rp(cfg["paths"]["revenue_reports_dir"]) / f"Payment_Report_{date}.md"
    write_output(out_path, "\n".join(lines))
    return 0


def cmd_war_room(cfg, args):
    print("Atlas Runtime - War Room (brief + dashboard + payment-report + content-pack)")
    print("=" * 60)
    cmd_brief(cfg, args)
    cmd_dashboard(cfg, args)
    cmd_payment_report(cfg, args)
    cmd_content_pack(cfg, args)

    m = compute_metrics(cfg)
    date = today()
    lines = ["# ALSAKKAF HOLDING GROUP", "", "# Atlas War Room Report", ""]
    lines.extend(doc_info_block("war-room"))
    lines.append(f"Generated: {now_iso()}")
    lines.append("")
    lines.append("## Snapshot")
    lines.append("")
    lines.append(f"- Active offer: {cfg['active_offer']} - ${cfg['price_usd']} {cfg['currency']}")
    lines.append(f"- Payment link: {cfg['payment_link']}")
    lines.append(f"- Leads found: {m['leads_found']} | Qualified: {m['leads_qualified']}")
    lines.append(f"- Outreach drafted: {m['outreach_drafted']} | Sent: {m['outreach_sent']}")
    lines.append(f"- Pipeline entries: {m['pipeline_active']} | Payments received: {m['payments_received']}")
    lines.append(f"- Revenue collected: ${m['revenue_collected']:.2f} {cfg['currency']}")
    lines.append(f"- Content drafted: {m['content_drafted']} | Posted: {m['content_published']}")
    lines.append("")
    lines.append("## Risks")
    lines.append("")
    for r in risk_lines(m, cfg):
        lines.append(f"- {r}")
    lines.append("")
    lines.append("## CEO Decisions Needed")
    lines.append("")
    for d in ceo_decisions(cfg):
        lines.append(f"- {d}")
    lines.append("")
    lines.append("## Next 5 Actions")
    lines.append("")
    for i, a in enumerate(next_five_actions(m), start=1):
        lines.append(f"{i}. {a}")
    lines.append("")
    lines.append("## Reports Generated This Run")
    lines.append("")
    lines.append(f"- Daily briefing: Atlas_Output/Daily_Briefing_{date}.md")
    lines.append(f"- Payment report: Atlas_Output/Revenue_Reports/Payment_Report_{date}.md")
    lines.append(f"- Content pack: Atlas_Output/Content_Packs/Content_Pack_{date}.md")
    lines.append("- Dashboard data: docs/atlas-dashboard-data.js")
    lines.append("")

    out_path = rp(cfg["paths"]["output_dir"]) / "Atlas_War_Room_Report.md"
    write_output(out_path, "\n".join(lines))
    print("=" * 60)
    print("WAR ROOM COMPLETE.")
    return 0


def cmd_revenue_sprint(cfg, args):
    print("Atlas Runtime - Generating PRJ-009 Revenue Sprint Report")
    m = compute_metrics(cfg)
    date = today()
    second = cfg.get("second_offer", {})

    landing = rp(cfg["paths"]["landing_page"])
    landing_text = ""
    if landing.exists():
        landing_text = landing.read_text(encoding="utf-8", errors="replace")
    has_399 = "399" in landing_text
    has_450 = "450" in landing_text
    has_link = cfg["payment_link"] in landing_text
    second_link = second.get("payment_link", "")
    has_second_link = bool(second_link) and second_link in landing_text

    proposals_dir = rp(cfg["paths"]["proposal_drafts_dir"])
    proposal_count = len(list(proposals_dir.glob("*.md"))) if proposals_dir.exists() else 0

    sprint_dir = rp(cfg["paths"].get("revenue_sprint_dir", ""))
    sprint_ready = sprint_dir.exists()

    lines = ["# ALSAKKAF HOLDING GROUP", "", "# PRJ-009 Revenue Sprint Report", ""]
    lines.extend(doc_info_block("revenue-sprint"))
    lines.append(f"Generated: {now_iso()}")
    lines.append("")
    lines.append("## Current Offers")
    lines.append("")
    lines.append(f"- {cfg['active_offer']} - ${cfg['price_usd']} {cfg['currency']} "
                 f"({cfg.get('offer_positioning', '')}) - ACTIVE payment link")
    if second:
        lines.append(f"- {second.get('name', '?')} - ${second.get('price_usd', '?')} "
                     f"{second.get('currency', 'USD')} ({second.get('positioning', '')}) - "
                     f"{second.get('payment_status', 'Request Custom Quote')}")
    lines.append("- Custom AOS Build - Request Quote")
    lines.append("")
    lines.append("## Website Publish Status")
    lines.append("")
    lines.append(f"- Landing page file exists: {'Yes' if landing.exists() else 'NO - missing'}")
    lines.append(f"- $399 offer on page: {'Yes' if has_399 else 'NO'}")
    lines.append(f"- $450 offer on page: {'Yes' if has_450 else 'NO'}")
    lines.append(f"- Approved $399 PayPal link on page: {'Yes' if has_link else 'NO'}")
    if second_link:
        lines.append(f"- Approved $450 PayPal link on page: {'Yes' if has_second_link else 'NO'}")
    lines.append("- Published to the public internet: manual CEO action - Atlas cannot verify or perform "
                 "publishing. Record the Day 1 publish decision in the sprint plan.")
    lines.append("")
    lines.append("## Lead Status")
    lines.append("")
    lines.append(f"- Real leads in Lead_Tracker.csv: {m['leads_found']} (sprint target: 25)")
    lines.append(f"- Qualified/scored: {m['leads_qualified']}")
    lines.append("")
    lines.append("## Outreach Status")
    lines.append("")
    lines.append(f"- Drafted: {m['outreach_drafted']} | CEO approved: {m['outreach_approved']} | "
                 f"Sent: {m['outreach_sent']} (sprint target: 5 sent)")
    lines.append("")
    lines.append("## Proposal Status")
    lines.append("")
    lines.append(f"- Proposal drafts generated locally: {proposal_count}")
    lines.append(f"- Real proposals sent: track in Client_Pipeline.csv (active entries: {m['pipeline_active']})")
    lines.append("")
    lines.append("## Payment Status")
    lines.append("")
    lines.append(f"- Payment links sent: {m['payment_links_sent']} | Payments received: {m['payments_received']}")
    lines.append(f"- Revenue collected: ${m['revenue_collected']:.2f} {cfg['currency']} (real tracker count, never a projection)")
    if second_link:
        lines.append("- $450 offer payment link: ACTIVE (approved by Founder)")
    else:
        lines.append("- $450 offer payment link: pending Founder creation and approval - Request Custom Quote until then")
    lines.append("")
    lines.append("## Next Actions")
    lines.append("")
    actions = []
    if not sprint_ready:
        actions.append("Sprint folder missing - restore 10_Revenue_Sprints/PRJ-009_First_Revenue_Sprint.")
    if m["leads_found"] == 0:
        actions.append("Open Day_1_Publish_and_Prepare.md: make the publish decision and choose the first market.")
        actions.append("Then Day_2_First_25_Leads.md: research 25 real leads into Lead_Tracker.csv.")
    elif m["outreach_sent"] == 0:
        actions.append("Run 'atlas.py first-5-outreach', personalize, approve, and send the first 5 messages manually.")
    elif m["payment_links_sent"] == 0 and m["payments_received"] == 0:
        actions.append("Follow up on sent outreach; prepare the first proposal (Day_4 file).")
        actions.append("On a confirmed yes: follow First_Payment_Checklist.md for the payment attempt.")
    else:
        actions.append("Work the live pipeline: follow-ups, proposal responses, and delivery preparation.")
    actions.append("Log every real-world result in the trackers the same day.")
    for i, a in enumerate(actions, start=1):
        lines.append(f"{i}. {a}")
    lines.append("")

    out_path = rp(cfg["paths"]["revenue_reports_dir"]) / "PRJ-009_Revenue_Sprint_Report.md"
    write_output(out_path, "\n".join(lines))
    return 0


def cmd_ai_agent_proposal(cfg, args):
    print("Atlas Runtime - Generating AI Agent Starter Pack Proposal Draft")
    second = cfg.get("second_offer", {})
    if not second:
        print("[FAIL] second_offer is missing from atlas_config.json")
        return 1
    client = args.client.strip() if getattr(args, "client", None) else "[Client Name]"
    date = today()

    lines = ["# AOS AI Services - AI Agent Starter Pack Proposal", ""]
    lines.append(f"Prepared for: {client}")
    lines.append(f"Date: {date}")
    lines.append("")
    lines.extend(doc_info_block("ai-agent-proposal"))
    lines.append("## Offer")
    lines.append("")
    lines.append(f"{second['name']} - ${second['price_usd']} {second.get('currency', 'USD')}")
    lines.append(f"Positioning: {second.get('positioning', '')}")
    lines.append(f"Delivery time: {second.get('delivery_time', '5-7 business days')} from completed intake answers")
    lines.append("")
    lines.append("## Your 3 AI Agents")
    lines.append("")
    for i, agent in enumerate(second.get("agents", []), start=1):
        lines.append(f"**{i}. {agent['name']}**")
        lines.append(f"- {agent['role']}")
        lines.append("- [Personalize: one concrete example from this client's business]")
        lines.append("")
    lines.append("## Everything You Receive")
    lines.append("")
    for item in second.get("deliverables", []):
        lines.append(f"- {item}")
    lines.append("")
    lines.append("## Honest Scope")
    lines.append("")
    lines.append("These are AI assistants working under your review and approval. This package does not include:")
    lines.append("")
    for item in second.get("never_promise", []):
        lines.append(f"- {item}")
    lines.append("")
    lines.append("If you need any of the above later, we scope and quote it separately.")
    lines.append("")
    lines.append("## Payment")
    lines.append("")
    if second.get("payment_link"):
        lines.append(f"Once you're ready to proceed: {second['payment_link']}")
        lines.append("")
        lines.append("Payments are processed in USD via PayPal's secure public checkout. This link is "
                     "sent only after interest is confirmed - never in first cold contact.")
    else:
        lines.append("Request Custom Quote - payment details are arranged by email once you confirm. "
                     "No payment link is included in this proposal; the payment link for this offer is "
                     "pending Founder approval.")
    lines.append("")
    lines.append("## Next Steps")
    lines.append("")
    lines.append("1. Reply to confirm, or ask any question first.")
    lines.append("2. Pay via the link above when ready (or ask us anything first).")
    lines.append("3. We send the intake form (about 20 minutes to complete).")
    lines.append("4. Delivery within 5-7 business days of your answers, then your 30-minute setup session.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("**Note:** This is a draft. Final proposal requires CEO review and full personalization "
                 "before sending to any real client. Template reference: AIAT-001.")
    lines.append("")
    lines.append(f"Generated: {now_iso()}")
    lines.append("")

    safe_name = re.sub(r"[^A-Za-z0-9_-]+", "_", client).strip("_") or "Blank"
    if safe_name == "Client_Name":
        out_path = rp(cfg["paths"]["proposal_drafts_dir"]) / "AI_Agent_Starter_Proposal.md"
    else:
        out_path = rp(cfg["paths"]["proposal_drafts_dir"]) / f"AI_Agent_Starter_Proposal_{safe_name}_{date}.md"
    write_output(out_path, "\n".join(lines))
    return 0


def cmd_ai_agent_delivery(cfg, args):
    print("Atlas Runtime - Generating AI Agent Starter Pack Delivery Checklist")
    second = cfg.get("second_offer", {})
    if not second:
        print("[FAIL] second_offer is missing from atlas_config.json")
        return 1
    client = args.client.strip() if getattr(args, "client", None) else "[Client Name]"

    lines = ["# AI Agent Starter Pack - Delivery Checklist", ""]
    lines.extend(doc_info_block("ai-agent-delivery"))
    lines.append(f"Client: {client}")
    lines.append(f"Offer: {second['name']} - ${second['price_usd']} {second.get('currency', 'USD')} "
                 f"({second.get('positioning', '')})")
    lines.append(f"Delivery time: {second.get('delivery_time', '5-7 business days')}")
    lines.append(f"Generated: {now_iso()}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Delivery Steps")
    lines.append("")
    lines.append("- [ ] Payment confirmed / quote agreed in writing (First_Payment_Checklist.md)")
    lines.append("- [ ] Intake form sent and complete answers received (AIAD-002)")
    for agent in second.get("agents", []):
        lines.append(f"- [ ] {agent['name']}: profile drafted (AIAD-003)")
        lines.append(f"      - [ ] {agent['name']}: prompt written and tested on 2 sample tasks (AIAD-004)")
    lines.append("- [ ] Agent task routing map completed (AIAD-005)")
    lines.append("- [ ] Business-specific workflow documented")
    lines.append("- [ ] Dashboard/reporting template prepared")
    lines.append("- [ ] Implementation guide personalized (AIAD-006)")
    lines.append("- [ ] Safety and approval rules customized (AIAD-007)")
    lines.append("- [ ] CEO review of the complete package")
    lines.append("- [ ] Handover document sent (AIAD-008)")
    lines.append("- [ ] 30-minute setup session booked and held")
    lines.append("- [ ] Revision window communicated (AIAD-009)")
    lines.append("- [ ] Client report sent (AIAT-007); lessons logged internally")
    lines.append("")
    lines.append("Full workflow: 01_Holding_Company/04_Operations/05_Client_Delivery/AI_Agent_Starter_Pack/")
    lines.append("")

    out_path = rp(cfg["paths"]["client_delivery_dir"]) / "AI_Agent_Starter_Delivery_Checklist.md"
    write_output(out_path, "\n".join(lines))
    return 0


def cmd_first_5_outreach(cfg, args):
    print("Atlas Runtime - Generating First 5 Outreach Execution Pack")
    m = compute_metrics(cfg)
    leads = m["raw"]["leads"]

    def lead_score(row):
        try:
            return float(str(row.get("Lead Score", "0")).strip() or 0)
        except ValueError:
            return 0.0

    top5 = sorted(leads, key=lead_score, reverse=True)[:5]

    lines = ["# First 5 Outreach - Execution Pack", ""]
    lines.extend(doc_info_block("first-5-outreach"))
    lines.append(f"Generated: {now_iso()}")
    lines.append("")
    lines.append("**CEO Approval Required.** Nothing here has been sent. Every message must be "
                 "personalized, approved, and sent manually by the Founder. No payment link in "
                 "first contact. Atlas never invents leads.")
    lines.append("")
    lines.append("---")
    lines.append("")

    if not top5:
        lines.append("## No Real Leads Yet")
        lines.append("")
        lines.append("Lead_Tracker.csv contains no real leads (placeholder/example rows are ignored). "
                     "This pack cannot name targets, because inventing leads is forbidden.")
        lines.append("")
        lines.append("Do this instead:")
        lines.append("")
        lines.append("1. Open Day_2_First_25_Leads.md in the PRJ-009 sprint folder.")
        lines.append("2. Research 25 real businesses in your chosen market; log them in Lead_Tracker.csv.")
        lines.append("3. Run 'atlas.py score-leads', then re-run this command for a lead-specific pack.")
        lines.append("")
        lines.append("Placeholder message frames to prepare with (personalize per real lead later):")
        lines.append("")
        frames = [
            ("$399 Workflow Pack - Email", "RLOUT/atlas.py outreach templates"),
            ("$450 AI Agent Pack - Email", "AIAT-002"),
            ("$450 AI Agent Pack - LinkedIn DM", "AIAT-003"),
            ("$450 AI Agent Pack - Instagram DM", "AIAT-004"),
        ]
        for name, ref in frames:
            lines.append(f"- {name}: template {ref}")
        lines.append("")
    else:
        lines.append("## Top 5 Leads From Lead_Tracker.csv (by Lead Score)")
        lines.append("")
        for i, lead in enumerate(top5, start=1):
            offer = lead.get("Offer Match", "").strip() or "Decide: $399 Workflow or $450 AI Agent"
            lines.append(f"### {i}. {lead.get('Company Name', '?')}")
            lines.append("")
            lines.append(f"- Lead ID: {lead.get('Lead ID', '?')} | Score: {lead.get('Lead Score', '?')} | "
                         f"Industry: {lead.get('Industry', '?')} | Location: {lead.get('City', '?')}, "
                         f"{lead.get('Country', '?')}")
            lines.append(f"- Problem observed: {lead.get('Problem Observed', '?')}")
            lines.append(f"- Offer match: {offer}")
            lines.append(f"- Contact path: {lead.get('Email', '') or lead.get('Social Link', '') or lead.get('Contact Page', '?')}")
            lines.append(f"- Template: {'AIAT-002/003/004' if 'agent' in offer.lower() else 'RLOUT series / atlas.py outreach'}")
            lines.append("- First line to write: reference the problem observed above - prove you looked.")
            lines.append("- Status: DRAFT - personalize in First_5_Outreach_Batch_Template.md, approve, send manually, log in Outreach_Tracker.csv.")
            lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("Working file for the actual messages: "
                 "01_Holding_Company/04_Operations/10_Revenue_Sprints/PRJ-009_First_Revenue_Sprint/"
                 "First_5_Outreach_Batch_Template.md")
    lines.append("")

    out_path = rp(cfg["paths"]["outreach_drafts_dir"]) / "First_5_Outreach_Execution_Pack.md"
    write_output(out_path, "\n".join(lines))
    return 0


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def build_parser():
    parser = argparse.ArgumentParser(prog="atlas.py", description="Atlas Runtime v1 - local CEO assistant tool.")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("health-check", help="Verify the launch package is present, safe, and readable.")
    sub.add_parser("brief", help="Generate a daily CEO briefing.")
    sub.add_parser("score-leads", help="Score real leads in Lead_Tracker.csv.")
    sub.add_parser("dashboard", help="Regenerate docs/atlas-dashboard-data.js.")

    p_proposal = sub.add_parser("proposal", help="Generate a proposal draft.")
    p_proposal.add_argument("--client", default=None, help="Client name (optional).")

    sub.add_parser("outreach", help="Generate outreach drafts (never sends).")
    sub.add_parser("content-pack", help="Generate a daily content pack.")

    p_delivery = sub.add_parser("delivery-checklist", help="Generate a client delivery checklist.")
    p_delivery.add_argument("--client", default=None, help="Client name (optional).")

    sub.add_parser("payment-report", help="Report pipeline payment status.")
    sub.add_parser("war-room", help="Run brief + dashboard + payment-report + content-pack.")

    sub.add_parser("revenue-sprint", help="Generate the PRJ-009 revenue sprint status report.")

    p_ai_proposal = sub.add_parser("ai-agent-proposal", help="Generate an AI Agent Starter Pack proposal draft.")
    p_ai_proposal.add_argument("--client", default=None, help="Client name (optional).")

    p_ai_delivery = sub.add_parser("ai-agent-delivery", help="Generate the AI Agent Starter Pack delivery checklist.")
    p_ai_delivery.add_argument("--client", default=None, help="Client name (optional).")

    sub.add_parser("first-5-outreach", help="Generate the first-5 outreach execution pack (drafts only).")

    return parser


COMMANDS = {
    "health-check": cmd_health_check,
    "brief": cmd_brief,
    "score-leads": cmd_score_leads,
    "dashboard": cmd_dashboard,
    "proposal": cmd_proposal,
    "outreach": cmd_outreach,
    "content-pack": cmd_content_pack,
    "delivery-checklist": cmd_delivery_checklist,
    "payment-report": cmd_payment_report,
    "war-room": cmd_war_room,
    "revenue-sprint": cmd_revenue_sprint,
    "ai-agent-proposal": cmd_ai_agent_proposal,
    "ai-agent-delivery": cmd_ai_agent_delivery,
    "first-5-outreach": cmd_first_5_outreach,
}


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    cfg = load_config()
    handler = COMMANDS[args.command]
    try:
        return handler(cfg, args)
    except Exception as exc:
        print(f"[FAIL] '{args.command}' failed: {exc}")
        print("Fix: check that the repo structure matches AOS Launch Version v1 and re-run.")
        return 1


if __name__ == "__main__":
    sys.exit(main())
